apiVersion: v1
kind: Service
metadata:
  name: rest-serv
  namespace: pruebas-mankar
spec:
  type: NodePort

  selector:
    app: rest-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30200
